### ISSUE TITLE
A DUB package for Phobos backports?

### ISSUE THREAD

**Issue by p0nce** [economicmodeling/containers#20]
There is way to have allocators works with all compilers, we did it for logger here: https://github.com/burner/logger/issues/22 to support multiple D front-ends.

- create a DUB package with `std.experimental.allocator`except renamed to `std.historical.allocator` (this avoid samey import conflicts with newer compilers)

- instead of `private import std.experimental.allocator.mallocator : Mallocator;`, use

```d
static if (front-end >= 2.069)
    import std.experimental.allocator;
else
    import std.historical.allocator;
```
I've checked and this isn't a problem for now but will be once a new DMD is out with allocators.
Such a package could be useful for other projects and would allow to compile allocators only once.

**Comment by Hackerpilot** [comment]
There's an experimental_allocator submodule for this now.
