### ISSUE TITLE
which version of allocator should I use?

### ISSUE THREAD

**Issue by Laeeth** [economicmodeling/containers#21]
Using allocator branch of Andrei's Phobos fork:
https://github.com/andralex/phobos.git

and DMD v 2.068

just copying over the std.experimental code and using stock Phobos otherwise I have a problem compiling (arch linux 64):

Compiling using dmd...
phobos/std/experimental/allocator/building_blocks/allocator_list.d(307,20): Error: no property 'expand' for type 'shared(Mallocator)'
phobos/std/experimental/allocator/building_blocks/allocator_list.d(529,28): Error: template instance std.experimental.allocator.building_blocks.allocator_list.AllocatorList!(Factory, Mallocator) error instantiating
src/app.d(14,19):        instantiated from here: AllocatorList!((a) => Region!Mallocator(1024 * 16), Mallocator)
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd_2068-847B9437DBA5F4B7C25C9B215DF0D8E9/ containers executable
Error executing command build:
dmd failed with exit code 1.

any suggestions?

**Comment by Hackerpilot** [comment]
`git submodule update --init --recursive`

**Comment by Laeeth** [comment]
doh!  thanks - that works.  Laeeth.

**Comment by Laeeth** [comment]
btw just out of curiosity do you use these containers with andrei's allocator in production yet ?  if I do and it goes horribly wrong, I will only have myself to blame of course.

**Comment by Hackerpilot** [comment]
Yes. They're used by some data processing code at EMSI as well as being used by DCD.

**Comment by Laeeth** [comment]
Thanks - I really appreciate your/EMSI's gift of these.  Makes my life much easier not to have to reinvent the wheel.  Laeeth.
