### ISSUE TITLE
Disabled Copy Constructors

### ISSUE THREAD

**Issue by nordlow** [economicmodeling/containers#25]
Returning a container from a function is currently not allowed because of

```D
this(this) @disable;
```

Is there a reason for this?

**Comment by DmitryOlshansky** [comment]
> HashSet needs to have move semantics (via postblit) for functional usage.

No - move semantic exactly require disabled postblit. Postblit is only issued on copy

**Comment by nordlow** [comment]
Ahh, my mistake.

**Comment by nordlow** [comment]
Ahh, my mistake. The reason for the error was another than I thought.
