### ISSUE TITLE
HashSet with class nothrow

### ISSUE THREAD

**Issue by burner** [economicmodeling/containers#43]
I'm trying to put a class into a HashSet but it keeps telling me something are not nothrow even though the code I created is nothrow. Maybe it's to late right now or I'm just stupid. Anyway, I could need some help.

```D
import containers.hashset;

import std.experimental.allocator.mallocator : Mallocator;

private hash_t stringToHash(string str) @safe pure nothrow @nogc {
	hash_t hash = 5381;
	return hash;
}

hash_t FooToHash(Foo e) pure @safe nothrow @nogc {
	return stringToHash(e.name);
}

class Foo {
	string name;
}

void main() {
	HashSet!(Foo, Mallocator, FooToHash) hs;
}
```

**Comment by Hackerpilot** [comment]
Looks like I need to remove some `nothrow` attributes from the containers because Object's methods aren't annotated properly.

**Comment by burner** [comment]
I created a PR fixing the issue and added some more testing.

* Are you guys come to DConf?
* If this passes your review and the CI could you create a new release soon. I really need a hashset and would like to include it through code.dlang.org. No pressure ;-)

**Comment by Hackerpilot** [comment]
I won't be coming to DConf this year. I'd say more about it but these Github issues are visible to the entire world.

**Comment by Hackerpilot** [comment]
https://github.com/economicmodeling/containers/releases/tag/v0.4.2

**Comment by burner** [comment]
thanks, that was fast
