### ISSUE TITLE
foreach_reverse support

### ISSUE THREAD

**Issue by sysint64** [economicmodeling/containers#77]
I have UnrolledList and I want to traverse this list in reverse order, but when I try to run this code:
`foreach_reverse (Widget widget; widgetOrdering)`
I get an error:

> invalid foreach aggregate this.widgetOrdering, define opApply(), range primitives, or use .tupleof

Also container doesn't have method `insertFront`.

**Comment by SirNickolas** [comment]
`UnrolledList` is a singly linked list. Traversing it in reverse order imposes either quadratic time complexity, or linear memory complexity. Please, consider using a different container for your task, or, if you are sure, implement the reversing yourself.

**Comment by sysint64** [comment]
Got it
